using System;
using System.Text.Json.Serialization;

namespace RU_NO_CRM_Functions.Models.Outbound
{

    public class DataverseAccountRequestMessage
    {

        public string? address1_latitudeODataCommunityDisplayV1FormattedValue { get; set; }
        public float? address1_latitude { get; set; }
        public string? mergedODataCommunityDisplayV1FormattedValue { get; set; }
        public bool? merged { get; set; }
        public string? statecodeODataCommunityDisplayV1FormattedValue { get; set; }
        public int? statecode { get; set; }
        public string? hbb_fjorretsomsetningiliterODataCommunityDisplayV1FormattedValue { get; set; }
        public int? hbb_fjorretsomsetningiliter { get; set; }
        public string? name { get; set; }
        public string? address1_county { get; set; }
        public string? modifiedonODataCommunityDisplayV1FormattedValue { get; set; }
        public string? modifiedonodatatype { get; set; }
        public DateTime modifiedon { get; set; }
        public string? address1_composite { get; set; }
        public string? address1_longitudeODataCommunityDisplayV1FormattedValue { get; set; }
        public float? address1_longitude { get; set; }
        public string? donotpostalmailODataCommunityDisplayV1FormattedValue { get; set; }
        public bool? donotpostalmail { get; set; }
        public string? accountratingcodeODataCommunityDisplayV1FormattedValue { get; set; }
        public int? accountratingcode { get; set; }
        public string? marketingonlyODataCommunityDisplayV1FormattedValue { get; set; }
        public bool? marketingonly { get; set; }
        public string? donotphoneODataCommunityDisplayV1FormattedValue { get; set; }
        public bool? donotphone { get; set; }
        public string? preferredcontactmethodcodeODataCommunityDisplayV1FormattedValue { get; set; }
        public int? preferredcontactmethodcode { get; set; }
        public string? _territoryid_valueODataCommunityDisplayV1FormattedValue { get; set; }
        public string? _territoryid_valueMicrosoftDynamicsCRMassociatednavigationproperty { get; set; }
        public string? _territoryid_valueMicrosoftDynamicsCRMlookuplogicalname { get; set; }
        public Guid? _territoryid_value { get; set; }
        public string? _ownerid_valueODataCommunityDisplayV1FormattedValue { get; set; }
        public string? _ownerid_valueMicrosoftDynamicsCRMassociatednavigationproperty { get; set; }
        public string? _ownerid_valueMicrosoftDynamicsCRMlookuplogicalname { get; set; }
        public Guid? _ownerid_value { get; set; }
        public string? hbb_sistebestillingODataCommunityDisplayV1FormattedValue { get; set; }
        public string? hbb_sistebestillingodatatype { get; set; }
        public DateTime? hbb_sistebestilling { get; set; }
        public string? description { get; set; }
        public string? customersizecodeODataCommunityDisplayV1FormattedValue { get; set; }
        public int? customersizecode { get; set; }
        public string? new_erdeltfelleskundeODataCommunityDisplayV1FormattedValue { get; set; }
        public bool? new_erdeltfelleskunde { get; set; }
        public string? hbb_organisasjonsnummer { get; set; }
        public string? openrevenue_dateODataCommunityDisplayV1FormattedValue { get; set; }
        public string? openrevenue_dateodatatype { get; set; }
        public DateTime? openrevenue_date { get; set; }
        public string? address2_addresstypecodeODataCommunityDisplayV1FormattedValue { get; set; }
        public int? address2_addresstypecode { get; set; }
        public string? msevtmgt_rentalcarproviderODataCommunityDisplayV1FormattedValue { get; set; }
        public int? msevtmgt_rentalcarprovider { get; set; }
        public string? businesstypecodeODataCommunityDisplayV1FormattedValue { get; set; }
        public int? businesstypecode { get; set; }
        public string? donotemailODataCommunityDisplayV1FormattedValue { get; set; }
        public bool? donotemail { get; set; }
        public string? address2_shippingmethodcodeODataCommunityDisplayV1FormattedValue { get; set; }
        public int? address2_shippingmethodcode { get; set; }
        public string? timezoneruleversionnumberODataCommunityDisplayV1FormattedValue { get; set; }
        public int? timezoneruleversionnumber { get; set; }
        public string? address1_addressidodatatype { get; set; }
        public Guid? address1_addressid { get; set; }
        public string? msdyn_gdproptoutODataCommunityDisplayV1FormattedValue { get; set; }
        public bool? msdyn_gdproptout { get; set; }
        public string? address2_freighttermscodeODataCommunityDisplayV1FormattedValue { get; set; }
        public int? address2_freighttermscode { get; set; }
        public string? statuscodeODataCommunityDisplayV1FormattedValue { get; set; }
        public int? statuscode { get; set; }
        public string? createdonODataCommunityDisplayV1FormattedValue { get; set; }
        public string? createdonodatatype { get; set; }
        public DateTime? createdon { get; set; }
        public string? msdyn_travelchargetypeODataCommunityDisplayV1FormattedValue { get; set; }
        public int? msdyn_travelchargetype { get; set; }
        public string? address2_county { get; set; }
        public string? donotbulkemailODataCommunityDisplayV1FormattedValue { get; set; }
        public bool? donotbulkemail { get; set; }
        public string? hbb_activity_spaceODataCommunityDisplayV1FormattedValue { get; set; }
        public int? hbb_activity_space { get; set; }
        public string? donotfaxODataCommunityDisplayV1FormattedValue { get; set; }
        public bool? donotfax { get; set; }
        public string? donotbulkpostalmailODataCommunityDisplayV1FormattedValue { get; set; }
        public bool? donotbulkpostalmail { get; set; }
        public string? _msdyn_salestaxcode_valueODataCommunityDisplayV1FormattedValue { get; set; }
        public string? _msdyn_salestaxcode_valueMicrosoftDynamicsCRMassociatednavigationproperty { get; set; }
        public string? _msdyn_salestaxcode_valueMicrosoftDynamicsCRMlookuplogicalname { get; set; }
        public Guid? _msdyn_salestaxcode_value { get; set; }
        public string? donotsendmmODataCommunityDisplayV1FormattedValue { get; set; }
        public bool? donotsendmm { get; set; }
        public string? versionnumberODataCommunityDisplayV1FormattedValue { get; set; }
        public string? versionnumberodatatype { get; set; }
        public int? versionnumber { get; set; }
        public string? followemailODataCommunityDisplayV1FormattedValue { get; set; }
        public bool? followemail { get; set; }
        public string? address1_line1 { get; set; }
        public string? creditonholdODataCommunityDisplayV1FormattedValue { get; set; }
        public bool? creditonhold { get; set; }
        public string? _transactioncurrencyid_valueODataCommunityDisplayV1FormattedValue { get; set; }
        public string? _transactioncurrencyid_valueMicrosoftDynamicsCRMassociatednavigationproperty { get; set; }
        public string? _transactioncurrencyid_valueMicrosoftDynamicsCRMlookuplogicalname { get; set; }
        public Guid? _transactioncurrencyid_value { get; set; }
        public string? accountidodatatype { get; set; }
        public Guid? accountid { get; set; }
        public string? msevtmgt_hotelgroupODataCommunityDisplayV1FormattedValue { get; set; }
        public int? msevtmgt_hotelgroup { get; set; }
        public string? hbb_prospectODataCommunityDisplayV1FormattedValue { get; set; }
        public bool? hbb_prospect { get; set; }
        public string? _modifiedby_valueODataCommunityDisplayV1FormattedValue { get; set; }
        public string? _modifiedby_valueMicrosoftDynamicsCRMlookuplogicalname { get; set; }
        public Guid? _modifiedby_value { get; set; }
        public string? hbb_faseODataCommunityDisplayV1FormattedValue { get; set; }
        public int? hbb_fase { get; set; }
        public string? shippingmethodcodeODataCommunityDisplayV1FormattedValue { get; set; }
        public int? shippingmethodcode { get; set; }
        public string? _createdby_valueODataCommunityDisplayV1FormattedValue { get; set; }
        public string? _createdby_valueMicrosoftDynamicsCRMlookuplogicalname { get; set; }
        public string? _createdby_value { get; set; }
        public string? hbb_grossistmodul_customernumber { get; set; }
        public string? address1_name { get; set; }
        public string? address1_city { get; set; }
        public string? territorycodeODataCommunityDisplayV1FormattedValue { get; set; }
        public int? territorycode { get; set; }
        public string? hbb_avtalefraODataCommunityDisplayV1FormattedValue { get; set; }
        public string? hbb_avtalefraodatatype { get; set; }
        public DateTime hbb_avtalefra { get; set; }
        public string? _owningteam_valueMicrosoftDynamicsCRMlookuplogicalname { get; set; }
        public Guid? _owningteam_value { get; set; }
        public string? msdyn_taxexemptODataCommunityDisplayV1FormattedValue { get; set; }
        public bool? msdyn_taxexempt { get; set; }
        public string? hbb_avtaletilODataCommunityDisplayV1FormattedValue { get; set; }
        public string? hbb_avtaletilodatatype { get; set; }
        public DateTime hbb_avtaletil { get; set; }
        public string? participatesinworkflowODataCommunityDisplayV1FormattedValue { get; set; }
        public bool? participatesinworkflow { get; set; }
        public string? accountclassificationcodeODataCommunityDisplayV1FormattedValue { get; set; }
        public int? accountclassificationcode { get; set; }
        public string? _owningbusinessunit_valueODataCommunityDisplayV1FormattedValue { get; set; }
        public string? _owningbusinessunit_valueMicrosoftDynamicsCRMassociatednavigationproperty { get; set; }
        public string? _owningbusinessunit_valueMicrosoftDynamicsCRMlookuplogicalname { get; set; }
        public Guid? _owningbusinessunit_value { get; set; }
        public string? address2_addressidodatatype { get; set; }
        public string? address2_addressid { get; set; }
        public string? address1_postalcode { get; set; }
        public string? hbb_omsetningODataCommunityDisplayV1FormattedValue { get; set; }
        public int? hbb_omsetning { get; set; }
        public string? opendeals_dateODataCommunityDisplayV1FormattedValue { get; set; }
        public string? opendeals_dateodatatype { get; set; }
        public DateTime opendeals_date { get; set; }
        public Guid? _hbb_owner_2_value { get; set; }
        public string? address1_telephone1 { get; set; }
        public string? hbb_hovedflaskel2 { get; set; }
        public string? pp_telefontekniker { get; set; }
        public string? stockexchange { get; set; }
        public string? hbb_license_alcohol_name { get; set; }
        public string? sic { get; set; }
        public string? address2_postalcode { get; set; }
        public long? sharesoutstanding { get; set; }
        public Guid? _msdyn_accountkpiid_value { get; set; }
        public string? address2_fax { get; set; }
        public string? websiteurl { get; set; }
        public string? hbb_hovedlptapp { get; set; }
        public string? paymenttermscode { get; set; }
        public string? new_tanklleveringsdag { get; set; }
        public string? pp_alias { get; set; }
        public Guid? _hbb_wholesaler_value { get; set; }
        public string? fax { get; set; }
        public string? address1_primarycontactname { get; set; }
        public long? crc81_produl { get; set; }
        public int? crc81_chainlevel { get; set; }
        public string? hbb_kundenummer { get; set; }
        public string? cr0c6_customers_customernumber { get; set; }
        public string? address2_telephone2 { get; set; }
        public string? address2_name { get; set; }
        public Guid? _msdyn_billingaccount_value { get; set; }
        public string? address2_stateorprovince { get; set; }
        public string? telephone1 { get; set; }
        public string? address1_addresstypecode { get; set; }
        public Guid? _modifiedonbehalfby_value { get; set; }
        public Guid? _createdonbehalfby_value { get; set; }
        public Guid? _cr0c6_chainarea_value { get; set; }
        public Guid? _originatingleadid_value { get; set; }
        public Guid? _pp_hovedaktivia_kunde_value { get; set; }
        public string? hbb_ifs_customer_number { get; set; }
        public string? address1_fax { get; set; }
        public string? address2_city { get; set; }
        public int? new_antalltrappetarn { get; set; }
        public double? address2_longitude { get; set; }
        public string? address2_postofficebox { get; set; }
        public string? address1_postofficebox { get; set; }
        public string? emailaddress1 { get; set; }
        public Guid? _createdbyexternalparty_value { get; set; }
        public string? emailaddress2 { get; set; }
        public string? hbb_hovedflaskel { get; set; }
        public string? hbb_tradesolution_lopenummer { get; set; }
        public string? address2_telephone3 { get; set; }
        public string? address2_telephone1 { get; set; }
        public string? hbb_gln { get; set; }
        public string? address1_country { get; set; }
        public string? address2_line3 { get; set; }
        public string? hbb_messagetodriver { get; set; }
        public string? telephone2 { get; set; }
        public Guid? _owninguser_value { get; set; }
        public Guid? _primarycontactid_value { get; set; }
        public string? _cr0c6_chainlevel4_value { get; set; }
        public string? msdyn_taxexemptnumber { get; set; }
        public string? hbb_invoice_mail { get; set; }
        public Guid? _modifiedbyexternalparty_value { get; set; }
        public Guid? _msdyn_salesaccelerationinsightid_value { get; set; }
        public Guid? _msa_managingpartnerid_value { get; set; }
        public int? numberofemployees { get; set; }
        public decimal? revenue { get; set; }
        public DateTimeOffset? hbb_licence_alc_fromdate { get; set; }
        public DateTimeOffset? hbb_licence_alc_todate { get; set; }
        public string? hbb_leverandr { get; set; }
        public Guid? _defaultpricelevelid_value { get; set; }
        public string? hbb_sapkundenummer { get; set; }
        public string? address2_primarycontactname { get; set; }
        public Guid? _hbb_assortment_code_value { get; set; }
        public string? crc81_profil { get; set; }
        public string? address1_telephone2 { get; set; }
        public Guid? _msdyn_preferredresource_value { get; set; }
        public string? hbb_bevilgningstype { get; set; }
        public Guid? _preferredsystemuserid_value { get; set; }
        public string? address1_telephone3 { get; set; }
        public string? address1_stateorprovince { get; set; }
        public string? _cr0c6_chainlevel2_value { get; set; }
        public string? address2_composite { get; set; }
        public string? new_omsetningiliter { get; set; }
        public string? address2_line2 { get; set; }
        public double? address2_latitude { get; set; }
        public Guid? _parentaccountid_value { get; set; }
        public string? address1_line3 { get; set; }
        public string? adx_modifiedbyusername { get; set; }
        public string? emailaddress3 { get; set; }
        public string? address2_line1 { get; set; }
        public string? accountnumber { get; set; }
        public string? address2_country { get; set; }
        public string? address1_line2 { get; set; }
        public Guid? _cr0c6_chainlevel3_value { get; set; }
        public Guid? _slaid_value { get; set; }
        public Guid? _msdyn_serviceterritory_value { get; set; }
        public string? yominame { get; set; }
        public string? primarysatoriid { get; set; }
        public Guid? _masterid_value { get; set; }
        public string? entityimage_url { get; set; }
        public int? new_antallkjoleskap { get; set; }
        public string? telephone3 { get; set; }
        public Guid? _cr0c6_chainlevel1_value { get; set; }
        public decimal? hbb_kredittgrense { get; set; }
        public string? territoryidodataassociationLink { get; set; }
        public string? territoryidodatanavigationLink { get; set; }
        public string? owneridodataassociationLink { get; set; }
        public string? owneridodatanavigationLink { get; set; }
        public string? msdyn_salestaxcodeodataassociationLink { get; set; }
        public string? msdyn_salestaxcodeodatanavigationLink { get; set; }
        public string? transactioncurrencyidodataassociationLink { get; set; }
        public string? transactioncurrencyidodatanavigationLink { get; set; }
        public string? owningbusinessunitodataassociationLink { get; set; }
        public string? owningbusinessunitodatanavigationLink { get; set; }
        public string? account_SocialInsightsConfigurationsodataassociationLink { get; set; }
        public string? account_SocialInsightsConfigurationsodatanavigationLink { get; set; }
        public string? account_principalobjectattributeaccessodataassociationLink { get; set; }
        public string? account_principalobjectattributeaccessodatanavigationLink { get; set; }
        public string? ModifiedByExternalPartyodataassociationLink { get; set; }
        public string? ModifiedByExternalPartyodatanavigationLink { get; set; }
        public string? createdbyodataassociationLink { get; set; }
        public string? createdbyodatanavigationLink { get; set; }
        public string? Account_Email_SendersAccountodataassociationLink { get; set; }
        public string? Account_Email_SendersAccountodatanavigationLink { get; set; }
        public string? Account_Email_EmailSenderodataassociationLink { get; set; }
        public string? Account_Email_EmailSenderodatanavigationLink { get; set; }
        public string? sla_account_slaodataassociationLink { get; set; }
        public string? sla_account_slaodatanavigationLink { get; set; }
        public string? modifiedbyodataassociationLink { get; set; }
        public string? modifiedbyodatanavigationLink { get; set; }
        public string? account_PostFollowsodataassociationLink { get; set; }
        public string? account_PostFollowsodatanavigationLink { get; set; }
        public string? account_PostRegardingsodataassociationLink { get; set; }
        public string? account_PostRegardingsodatanavigationLink { get; set; }
        public string? account_PostRolesodataassociationLink { get; set; }
        public string? account_PostRolesodatanavigationLink { get; set; }
        public string? entityimageid_imagedescriptorodataassociationLink { get; set; }
        public string? entityimageid_imagedescriptorodatanavigationLink { get; set; }
        public string? Account_AsyncOperationsodataassociationLink { get; set; }
        public string? Account_AsyncOperationsodatanavigationLink { get; set; }
        public string? Account_DuplicateBaseRecordodataassociationLink { get; set; }
        public string? Account_DuplicateBaseRecordodatanavigationLink { get; set; }
        public string? createdonbehalfbyodataassociationLink { get; set; }
        public string? createdonbehalfbyodatanavigationLink { get; set; }
        public string? Account_MailboxTrackingFolderodataassociationLink { get; set; }
        public string? Account_MailboxTrackingFolderodatanavigationLink { get; set; }
        public string? slakpiinstance_accountodataassociationLink { get; set; }
        public string? slakpiinstance_accountodatanavigationLink { get; set; }
        public string? slainvokedid_account_slaodataassociationLink { get; set; }
        public string? slainvokedid_account_slaodatanavigationLink { get; set; }
        public string? Account_BulkDeleteFailuresodataassociationLink { get; set; }
        public string? Account_BulkDeleteFailuresodatanavigationLink { get; set; }
        public string? userentityinstancedata_accountodataassociationLink { get; set; }
        public string? userentityinstancedata_accountodatanavigationLink { get; set; }
        public string? account_customer_relationship_customerodataassociationLink { get; set; }
        public string? account_customer_relationship_customerodatanavigationLink { get; set; }
        public string? CreatedByExternalPartyodataassociationLink { get; set; }
        public string? CreatedByExternalPartyodatanavigationLink { get; set; }
        public string? Account_DuplicateMatchingRecordodataassociationLink { get; set; }
        public string? Account_DuplicateMatchingRecordodatanavigationLink { get; set; }
        public string? account_activity_partiesodataassociationLink { get; set; }
        public string? account_activity_partiesodatanavigationLink { get; set; }
        public string? account_connections1odataassociationLink { get; set; }
        public string? account_connections1odatanavigationLink { get; set; }
        public string? stageid_processstageodataassociationLink { get; set; }
        public string? stageid_processstageodatanavigationLink { get; set; }
        public string? account_customer_relationship_partnerodataassociationLink { get; set; }
        public string? account_customer_relationship_partnerodatanavigationLink { get; set; }
        public string? modifiedonbehalfbyodataassociationLink { get; set; }
        public string? modifiedonbehalfbyodatanavigationLink { get; set; }
        public string? accountleads_associationodataassociationLink { get; set; }
        public string? accountleads_associationodatanavigationLink { get; set; }
        public string? account_bookableresource_AccountIdodataassociationLink { get; set; }
        public string? account_bookableresource_AccountIdodatanavigationLink { get; set; }
        public string? CreatedAccount_BulkOperationLogs2odataassociationLink { get; set; }
        public string? CreatedAccount_BulkOperationLogs2odatanavigationLink { get; set; }
        public string? SourceAccount_BulkOperationLogsodataassociationLink { get; set; }
        public string? SourceAccount_BulkOperationLogsodatanavigationLink { get; set; }
        public string? account_customer_opportunity_rolesodataassociationLink { get; set; }
        public string? account_customer_opportunity_rolesodatanavigationLink { get; set; }
        public string? order_customer_accountsodataassociationLink { get; set; }
        public string? order_customer_accountsodatanavigationLink { get; set; }
        public string? account_actioncardodataassociationLink { get; set; }
        public string? account_actioncardodatanavigationLink { get; set; }
        public string? Account_ActivityPointersodataassociationLink { get; set; }
        public string? Account_ActivityPointersodatanavigationLink { get; set; }
        public string? Account_AnnotationodataassociationLink { get; set; }
        public string? Account_AnnotationodatanavigationLink { get; set; }
        public string? Account_AppointmentsodataassociationLink { get; set; }
        public string? Account_AppointmentsodatanavigationLink { get; set; }
        public string? account_BulkOperationsodataassociationLink { get; set; }
        public string? account_BulkOperationsodatanavigationLink { get; set; }
        public string? account_CampaignResponsesodataassociationLink { get; set; }
        public string? account_CampaignResponsesodatanavigationLink { get; set; }
        public string? account_connections2odataassociationLink { get; set; }
        public string? account_connections2odatanavigationLink { get; set; }
        public string? Account_CustomerAddressodataassociationLink { get; set; }
        public string? Account_CustomerAddressodatanavigationLink { get; set; }
        public string? Account_EmailsodataassociationLink { get; set; }
        public string? Account_EmailsodatanavigationLink { get; set; }
        public string? Account_FaxesodataassociationLink { get; set; }
        public string? Account_FaxesodatanavigationLink { get; set; }
        public string? account_IncidentResolutionsodataassociationLink { get; set; }
        public string? account_IncidentResolutionsodatanavigationLink { get; set; }
        public string? Account_LettersodataassociationLink { get; set; }
        public string? Account_LettersodatanavigationLink { get; set; }
        public string? account_li_inmailsodataassociationLink { get; set; }
        public string? account_li_inmailsodatanavigationLink { get; set; }
        public string? account_li_messagesodataassociationLink { get; set; }
        public string? account_li_messagesodatanavigationLink { get; set; }
        public string? account_li_pointdrivepresentationviewedsodataassociationLink { get; set; }
        public string? account_li_pointdrivepresentationviewedsodatanavigationLink { get; set; }
        public string? account_msdyn_bookingalertsodataassociationLink { get; set; }
        public string? account_msdyn_bookingalertsodatanavigationLink { get; set; }
        public string? account_OpportunityClosesodataassociationLink { get; set; }
        public string? account_OpportunityClosesodatanavigationLink { get; set; }
        public string? account_OrderClosesodataassociationLink { get; set; }
        public string? account_OrderClosesodatanavigationLink { get; set; }
        public string? Account_PhonecallsodataassociationLink { get; set; }
        public string? Account_PhonecallsodatanavigationLink { get; set; }
        public string? Account_ProcessSessionsodataassociationLink { get; set; }
        public string? Account_ProcessSessionsodatanavigationLink { get; set; }
        public string? account_QuoteClosesodataassociationLink { get; set; }
        public string? account_QuoteClosesodatanavigationLink { get; set; }
        public string? Account_RecurringAppointmentMastersodataassociationLink { get; set; }
        public string? Account_RecurringAppointmentMastersodatanavigationLink { get; set; }
        public string? Account_SharepointDocumentodataassociationLink { get; set; }
        public string? Account_SharepointDocumentodatanavigationLink { get; set; }
        public string? Account_SharepointDocumentLocationodataassociationLink { get; set; }
        public string? Account_SharepointDocumentLocationodatanavigationLink { get; set; }
        public string? Account_SocialActivitiesodataassociationLink { get; set; }
        public string? Account_SocialActivitiesodatanavigationLink { get; set; }
        public string? Account_SyncErrorsodataassociationLink { get; set; }
        public string? Account_SyncErrorsodatanavigationLink { get; set; }
        public string? Account_TasksodataassociationLink { get; set; }
        public string? Account_TasksodatanavigationLink { get; set; }
        public string? contact_customer_accountsodataassociationLink { get; set; }
        public string? contact_customer_accountsodatanavigationLink { get; set; }
        public string? cr0c6_SalesOrder_Account_AccountodataassociationLink { get; set; }
        public string? cr0c6_SalesOrder_Account_AccountodatanavigationLink { get; set; }
        public string? hbb_account_bookableresourcebookingodataassociationLink { get; set; }
        public string? hbb_account_bookableresourcebookingodatanavigationLink { get; set; }
        public string? hbb_account_hbb_ordreodataassociationLink { get; set; }
        public string? hbb_account_hbb_ordreodatanavigationLink { get; set; }
        public string? hbb_account_hbb_produkt_KundeodataassociationLink { get; set; }
        public string? hbb_account_hbb_produkt_KundeodatanavigationLink { get; set; }
        public string? hbb_account_hbb_salgstall_KundeodataassociationLink { get; set; }
        public string? hbb_account_hbb_salgstall_KundeodatanavigationLink { get; set; }
        public string? invoice_customer_accountsodataassociationLink { get; set; }
        public string? invoice_customer_accountsodatanavigationLink { get; set; }
        public string? lead_customer_accountsodataassociationLink { get; set; }
        public string? lead_customer_accountsodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_actual_AccountCustomerodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_actual_AccountCustomerodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_actual_AccountVendorodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_actual_AccountVendorodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_actual_ServiceAccountodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_actual_ServiceAccountodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_agreement_BillingAccountodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_agreement_BillingAccountodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_agreement_ServiceAccountodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_agreement_ServiceAccountodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_entitlementapplication_serviceaccountodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_entitlementapplication_serviceaccountodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_payment_AccountodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_payment_AccountodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_purchaseorder_VendorodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_purchaseorder_VendorodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_requirementresourcepreference_AccountodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_requirementresourcepreference_AccountodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_rma_BillingAccountodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_rma_BillingAccountodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_rma_ServiceAccountodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_rma_ServiceAccountodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_rmaproduct_ChangeownershipodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_rmaproduct_ChangeownershipodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_rmaproduct_ReturntoVendorodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_rmaproduct_ReturntoVendorodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_rtv_VendorodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_rtv_VendorodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_workorderresourcerestriction_AccountodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_workorderresourcerestriction_AccountodatanavigationLink { get; set; }
        public string? msdyn_account_opportunityproduct_ServiceAccountodataassociationLink { get; set; }
        public string? msdyn_account_opportunityproduct_ServiceAccountodatanavigationLink { get; set; }
        public string? msdyn_account_product_DefaultVendorodataassociationLink { get; set; }
        public string? msdyn_account_product_DefaultVendorodatanavigationLink { get; set; }
        public string? msdyn_account_quote_AccountodataassociationLink { get; set; }
        public string? msdyn_account_quote_AccountodatanavigationLink { get; set; }
        public string? msdyn_account_quotedetail_ServiceAccountodataassociationLink { get; set; }
        public string? msdyn_account_quotedetail_ServiceAccountodatanavigationLink { get; set; }
        public string? msdyn_account_salesorder_AccountodataassociationLink { get; set; }
        public string? msdyn_account_salesorder_AccountodatanavigationLink { get; set; }
        public string? msdyn_geofence_accountodataassociationLink { get; set; }
        public string? msdyn_geofence_accountodatanavigationLink { get; set; }
        public string? opportunity_customer_accountsodataassociationLink { get; set; }
        public string? opportunity_customer_accountsodatanavigationLink { get; set; }
        public string? opportunity_parent_accountodataassociationLink { get; set; }
        public string? opportunity_parent_accountodatanavigationLink { get; set; }
        public string? quote_customer_accountsodataassociationLink { get; set; }
        public string? quote_customer_accountsodatanavigationLink { get; set; }
        public string? SocialActivity_PostAuthor_accountsodataassociationLink { get; set; }
        public string? SocialActivity_PostAuthor_accountsodatanavigationLink { get; set; }
        public string? SocialActivity_PostAuthorAccount_accountsodataassociationLink { get; set; }
        public string? SocialActivity_PostAuthorAccount_accountsodatanavigationLink { get; set; }
        public string? Socialprofile_customer_accountsodataassociationLink { get; set; }
        public string? Socialprofile_customer_accountsodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_iotdevice_AccountodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_iotdevice_AccountodatanavigationLink { get; set; }
        public string? originatingleadidodataassociationLink { get; set; }
        public string? originatingleadidodatanavigationLink { get; set; }
        public string? cr0c6_chainareaodataassociationLink { get; set; }
        public string? cr0c6_chainareaodatanavigationLink { get; set; }
        public string? hbb_assortment_codeodataassociationLink { get; set; }
        public string? hbb_assortment_codeodatanavigationLink { get; set; }
        public string? hbb_TechnicianodataassociationLink { get; set; }
        public string? hbb_TechnicianodatanavigationLink { get; set; }
        public string? msdyn_PreferredResourceodataassociationLink { get; set; }
        public string? msdyn_PreferredResourceodatanavigationLink { get; set; }
        public string? msdyn_workhourtemplateodataassociationLink { get; set; }
        public string? msdyn_workhourtemplateodatanavigationLink { get; set; }
        public string? msdyn_serviceterritoryodataassociationLink { get; set; }
        public string? msdyn_serviceterritoryodatanavigationLink { get; set; }
        public string? defaultpricelevelidodataassociationLink { get; set; }
        public string? defaultpricelevelidodatanavigationLink { get; set; }
        public string? preferredsystemuseridodataassociationLink { get; set; }
        public string? preferredsystemuseridodatanavigationLink { get; set; }
        public string? owningteamodataassociationLink { get; set; }
        public string? owningteamodatanavigationLink { get; set; }
        public string? owninguserodataassociationLink { get; set; }
        public string? owninguserodatanavigationLink { get; set; }
        public string? msdyn_msdyn_functionallocation_accountodataassociationLink { get; set; }
        public string? msdyn_msdyn_functionallocation_accountodatanavigationLink { get; set; }
        public string? lead_parent_accountodataassociationLink { get; set; }
        public string? lead_parent_accountodatanavigationLink { get; set; }
        public string? listaccount_associationodataassociationLink { get; set; }
        public string? listaccount_associationodatanavigationLink { get; set; }
        public string? BulkOperation_Logs_AccountsodataassociationLink { get; set; }
        public string? BulkOperation_Logs_AccountsodatanavigationLink { get; set; }
        public string? CampaignActivity_Logs_AccountsodataassociationLink { get; set; }
        public string? CampaignActivity_Logs_AccountsodatanavigationLink { get; set; }
        public string? hbb_account_msdyn_workorder_teknikerodataassociationLink { get; set; }
        public string? hbb_account_msdyn_workorder_teknikerodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_workorder_BillingAccountodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_workorder_BillingAccountodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_workorder_ServiceAccountodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_workorder_ServiceAccountodatanavigationLink { get; set; }
        public string? pp_Hovedaktivia_KundeodataassociationLink { get; set; }
        public string? pp_Hovedaktivia_KundeodatanavigationLink { get; set; }
        public string? pp_BookableResourceBooking_Kunde_AccountodataassociationLink { get; set; }
        public string? pp_BookableResourceBooking_Kunde_AccountodatanavigationLink { get; set; }
        public string? pp_msdyn_workorderincident_account_workorderodataassociationLink { get; set; }
        public string? pp_msdyn_workorderincident_account_workorderodatanavigationLink { get; set; }
        public string? pp_Standardsvinn_Kunde_AccountodataassociationLink { get; set; }
        public string? pp_Standardsvinn_Kunde_AccountodatanavigationLink { get; set; }
        public string? hbb_delivery_place_imageid_imagedescriptorodataassociationLink { get; set; }
        public string? hbb_delivery_place_imageid_imagedescriptorodatanavigationLink { get; set; }
        public string? account_FileAttachmentsodataassociationLink { get; set; }
        public string? account_FileAttachmentsodatanavigationLink { get; set; }
        public string? hbb_imageofcustomersmenuid_imagedescriptorodataassociationLink { get; set; }
        public string? hbb_imageofcustomersmenuid_imagedescriptorodatanavigationLink { get; set; }
        public string? msevtmgt_account_msevtmgt_eventvendor_AccountodataassociationLink { get; set; }
        public string? msevtmgt_account_msevtmgt_eventvendor_AccountodatanavigationLink { get; set; }
        public string? msevtmgt_account_msevtmgt_sponsorship_SponsorodataassociationLink { get; set; }
        public string? msevtmgt_account_msevtmgt_sponsorship_SponsorodatanavigationLink { get; set; }
        public string? account_msdyn_ocliveworkitemsodataassociationLink { get; set; }
        public string? account_msdyn_ocliveworkitemsodatanavigationLink { get; set; }
        public string? account_msdyn_ocsessionsodataassociationLink { get; set; }
        public string? account_msdyn_ocsessionsodatanavigationLink { get; set; }
        public string? hbb_account_hbb_arrangement_kundeodataassociationLink { get; set; }
        public string? hbb_account_hbb_arrangement_kundeodatanavigationLink { get; set; }
        public string? msdyn_salessuggestion_accountodataassociationLink { get; set; }
        public string? msdyn_salessuggestion_accountodatanavigationLink { get; set; }
        public string? msdyn_swarm_accountodataassociationLink { get; set; }
        public string? msdyn_swarm_accountodatanavigationLink { get; set; }
        public string? msdyn_salesaccelerationinsights_accountodataassociationLink { get; set; }
        public string? msdyn_salesaccelerationinsights_accountodatanavigationLink { get; set; }
        public string? msdyn_salesaccelerationinsightidodataassociationLink { get; set; }
        public string? msdyn_salesaccelerationinsightidodatanavigationLink { get; set; }
        public string? account_PostsodataassociationLink { get; set; }
        public string? account_PostsodatanavigationLink { get; set; }
        public string? account_chatsodataassociationLink { get; set; }
        public string? account_chatsodatanavigationLink { get; set; }
        public string? msdyn_playbookinstance_accountodataassociationLink { get; set; }
        public string? msdyn_playbookinstance_accountodatanavigationLink { get; set; }
        public string? pp_msdyn_bookableresourcebookingquicknote_acodataassociationLink { get; set; }
        public string? pp_msdyn_bookableresourcebookingquicknote_acodatanavigationLink { get; set; }
        public string? msdyn_msdyn_preferredagent_account_msdyn_recordIdodataassociationLink { get; set; }
        public string? msdyn_msdyn_preferredagent_account_msdyn_recordIdodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_ocliveworkitem_CustomerodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_ocliveworkitem_CustomerodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_liveconversation_CustomerodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_liveconversation_CustomerodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_accountkpiitem_accountidodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_accountkpiitem_accountidodatanavigationLink { get; set; }
        public string? msdyn_accountkpiidodataassociationLink { get; set; }
        public string? msdyn_accountkpiidodatanavigationLink { get; set; }
        public string? msdyn_account_dailyaccountkpiitem_entityidodataassociationLink { get; set; }
        public string? msdyn_account_dailyaccountkpiitem_entityidodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_nottoexceed_accountodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_nottoexceed_accountodatanavigationLink { get; set; }
        public string? hbb_account_hbb_portalorder_customerodataassociationLink { get; set; }
        public string? hbb_account_hbb_portalorder_customerodatanavigationLink { get; set; }
        public string? new_account_msdyn_orgchartnodeupdated_msdyn_parentrecordupdatedodataassociationLink { get; set; }
        public string? new_account_msdyn_orgchartnodeupdated_msdyn_parentrecordupdatedodatanavigationLink { get; set; }
        public string? account_msdyn_copilottranscriptsodataassociationLink { get; set; }
        public string? account_msdyn_copilottranscriptsodatanavigationLink { get; set; }
        public string? hbb_account_hbb_customer_assortment_exception_chainodataassociationLink { get; set; }
        public string? hbb_account_hbb_customer_assortment_exception_chainodatanavigationLink { get; set; }
        public string? hbb_assortmentcode_chain_AccountodataassociationLink { get; set; }
        public string? hbb_assortmentcode_chain_AccountodatanavigationLink { get; set; }
        public string? new_account_new_customerassortment_AccountIdodataassociationLink { get; set; }
        public string? new_account_new_customerassortment_AccountIdodatanavigationLink { get; set; }
        public string? masteridodataassociationLink { get; set; }
        public string? masteridodatanavigationLink { get; set; }
        public string? account_master_accountodataassociationLink { get; set; }
        public string? account_master_accountodatanavigationLink { get; set; }
        public string? parentaccountidodataassociationLink { get; set; }
        public string? parentaccountidodatanavigationLink { get; set; }
        public string? account_parent_accountodataassociationLink { get; set; }
        public string? account_parent_accountodatanavigationLink { get; set; }
        public string? cr0c6_chainlevel1odataassociationLink { get; set; }
        public string? cr0c6_chainlevel1odatanavigationLink { get; set; }
        public string? cr0c6_Account_chainlevel1_AccountodataassociationLink { get; set; }
        public string? cr0c6_Account_chainlevel1_AccountodatanavigationLink { get; set; }
        public string? cr0c6_chainlevel2odataassociationLink { get; set; }
        public string? cr0c6_chainlevel2odatanavigationLink { get; set; }
        public string? cr0c6_Account_chainlevel2_AccountodataassociationLink { get; set; }
        public string? cr0c6_Account_chainlevel2_AccountodatanavigationLink { get; set; }
        public string? cr0c6_chainlevel3odataassociationLink { get; set; }
        public string? cr0c6_chainlevel3odatanavigationLink { get; set; }
        public string? cr0c6_Account_chainlevel3_AccountodataassociationLink { get; set; }
        public string? cr0c6_Account_chainlevel3_AccountodatanavigationLink { get; set; }
        public string? cr0c6_chainlevel4odataassociationLink { get; set; }
        public string? cr0c6_chainlevel4odatanavigationLink { get; set; }
        public string? cr0c6_Account_chainlevel4_AccountodataassociationLink { get; set; }
        public string? cr0c6_Account_chainlevel4_AccountodatanavigationLink { get; set; }
        public string? msdyn_billingaccount_accountodataassociationLink { get; set; }
        public string? msdyn_billingaccount_accountodatanavigationLink { get; set; }
        public string? msdyn_account_account_BillingAccountodataassociationLink { get; set; }
        public string? msdyn_account_account_BillingAccountodatanavigationLink { get; set; }
        public string? hbb_wholesalerodataassociationLink { get; set; }
        public string? hbb_wholesalerodatanavigationLink { get; set; }
        public string? hbb_Account_wholesaler_AccountodataassociationLink { get; set; }
        public string? hbb_Account_wholesaler_AccountodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_mostcontacted_regardingObjectIdodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_mostcontacted_regardingObjectIdodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_mostcontactedby_regardingObjectIdodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_mostcontactedby_regardingObjectIdodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_customerasset_AccountodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_customerasset_AccountodatanavigationLink { get; set; }
        public string? pp_pp_utleie_accountId_accountodataassociationLink { get; set; }
        public string? pp_pp_utleie_accountId_accountodatanavigationLink { get; set; }
        public string? powerpagecomponent_mspp_webrole_accountodataassociationLink { get; set; }
        public string? powerpagecomponent_mspp_webrole_accountodatanavigationLink { get; set; }
        public string? hbb_chain_product_Kjede_AccountodataassociationLink { get; set; }
        public string? hbb_chain_product_Kjede_AccountodatanavigationLink { get; set; }
        public string? hbb_customerproduct_Kunde_AccountodataassociationLink { get; set; }
        public string? hbb_customerproduct_Kunde_AccountodatanavigationLink { get; set; }
        public string? primarycontactidodataassociationLink { get; set; }
        public string? primarycontactidodatanavigationLink { get; set; }
        public string? cr0c6_areas_areaforchain_AccountodataassociationLink { get; set; }
        public string? cr0c6_areas_areaforchain_AccountodatanavigationLink { get; set; }
        public string? cr0c6_customerspace_Kunde_AccountodataassociationLink { get; set; }
        public string? cr0c6_customerspace_Kunde_AccountodatanavigationLink { get; set; }
        public string? hbb_Owner_2_systemuserodataassociationLink { get; set; }
        public string? hbb_Owner_2_systemuserodatanavigationLink { get; set; }
        public string? hbb_Owner_2_teamodataassociationLink { get; set; }
        public string? hbb_Owner_2_teamodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_warranty_WarrantyHolderodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_warranty_WarrantyHolderodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_warranty_WarrantyProviderodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_warranty_WarrantyProviderodatanavigationLink { get; set; }
        public string? msdyn_msdyn_warranty_accountodataassociationLink { get; set; }
        public string? msdyn_msdyn_warranty_accountodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_insurance_InsuranceCarrierodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_insurance_InsuranceCarrierodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_tradecoverage_AccountodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_tradecoverage_AccountodatanavigationLink { get; set; }
        public string? msdyn_msdyn_insurance_PolicyHolder_accountodataassociationLink { get; set; }
        public string? msdyn_msdyn_insurance_PolicyHolder_accountodatanavigationLink { get; set; }
        public string? account_msfp_alertsodataassociationLink { get; set; }
        public string? account_msfp_alertsodatanavigationLink { get; set; }
        public string? account_msfp_surveyinvitesodataassociationLink { get; set; }
        public string? account_msfp_surveyinvitesodatanavigationLink { get; set; }
        public string? account_msfp_surveyresponsesodataassociationLink { get; set; }
        public string? account_msfp_surveyresponsesodatanavigationLink { get; set; }
        public string? contractlineitem_customer_accountsodataassociationLink { get; set; }
        public string? contractlineitem_customer_accountsodatanavigationLink { get; set; }
        public string? contract_billingcustomer_accountsodataassociationLink { get; set; }
        public string? contract_billingcustomer_accountsodatanavigationLink { get; set; }
        public string? contract_customer_accountsodataassociationLink { get; set; }
        public string? contract_customer_accountsodatanavigationLink { get; set; }
        public string? incident_customer_accountsodataassociationLink { get; set; }
        public string? incident_customer_accountsodatanavigationLink { get; set; }
        public string? account_entitlement_AccountodataassociationLink { get; set; }
        public string? account_entitlement_AccountodatanavigationLink { get; set; }
        public string? account_entitlement_CustomerodataassociationLink { get; set; }
        public string? account_entitlement_CustomerodatanavigationLink { get; set; }
        public string? preferredequipmentidodataassociationLink { get; set; }
        public string? preferredequipmentidodatanavigationLink { get; set; }
        public string? preferredserviceidodataassociationLink { get; set; }
        public string? preferredserviceidodatanavigationLink { get; set; }
        public string? Account_ServiceAppointmentsodataassociationLink { get; set; }
        public string? Account_ServiceAppointmentsodatanavigationLink { get; set; }
        public string? adx_website_sponsorodataassociationLink { get; set; }
        public string? adx_website_sponsorodatanavigationLink { get; set; }
        public string? msa_managingpartneridodataassociationLink { get; set; }
        public string? msa_managingpartneridodatanavigationLink { get; set; }
        public string? msa_account_managingpartnerodataassociationLink { get; set; }
        public string? msa_account_managingpartnerodatanavigationLink { get; set; }
        public string? msa_contact_managingpartnerodataassociationLink { get; set; }
        public string? msa_contact_managingpartnerodatanavigationLink { get; set; }
        public string? msa_account_incidentodataassociationLink { get; set; }
        public string? msa_account_incidentodatanavigationLink { get; set; }
        public string? msa_partner_opportunityodataassociationLink { get; set; }
        public string? msa_partner_opportunityodatanavigationLink { get; set; }
        public string? account_adx_alertsubscriptionsodataassociationLink { get; set; }
        public string? account_adx_alertsubscriptionsodatanavigationLink { get; set; }
        public string? account_adx_inviteredemptionsodataassociationLink { get; set; }
        public string? account_adx_inviteredemptionsodatanavigationLink { get; set; }
        public string? adx_invitation_assigntoaccountodataassociationLink { get; set; }
        public string? adx_invitation_assigntoaccountodatanavigationLink { get; set; }
        public string? adx_webrole_accountodataassociationLink { get; set; }
        public string? adx_webrole_accountodatanavigationLink { get; set; }
        public string? account_adx_portalcommentsodataassociationLink { get; set; }
        public string? account_adx_portalcommentsodatanavigationLink { get; set; }
        public string? adx_AccountContentAccessLevelodataassociationLink { get; set; }
        public string? adx_AccountContentAccessLevelodatanavigationLink { get; set; }
        public string? adx_accountproductodataassociationLink { get; set; }
        public string? adx_accountproductodatanavigationLink { get; set; }
        public string? adx_account_badgeodataassociationLink { get; set; }
        public string? adx_account_badgeodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_salesroutingrun_targetobjectodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_salesroutingrun_targetobjectodatanavigationLink { get; set; }
        public string? msdyn_msdyn_salescopilotinsight_account_msdyn_targetentityidodataassociationLink { get; set; }
        public string? msdyn_msdyn_salescopilotinsight_account_msdyn_targetentityidodatanavigationLink { get; set; }
        public string? msdyn_account_msdyn_aicontactsuggestion_sourcerecordodataassociationLink { get; set; }
        public string? msdyn_account_msdyn_aicontactsuggestion_sourcerecordodatanavigationLink { get; set; }
        public string? msdyn_msdyn_conversationparticipantinsights_account_msdyn_userodataassociationLink { get; set; }
        public string? msdyn_msdyn_conversationparticipantinsights_account_msdyn_userodatanavigationLink { get; set; }
        [JsonPropertyName("new_kategori@OData.Community.Display.V1.FormattedValue")]
        public string? new_kategori_value { get; set; }

        [JsonPropertyName("hbb_type@OData.Community.Display.V1.FormattedValue")]
        public string? hbb_type_value { get; set; }

        public int? hbb_type { get; set; }

        [JsonPropertyName("creditlimit@OData.Community.Display.V1.FormattedValue")]
        public string? creditlimitFormattedValue { get; set; }

        public decimal? creditlimit { get; set; }

        [JsonPropertyName("cr0c6_warehouse")]
        public long? WareHouseId { get; set; }

        [JsonPropertyName("cr0c6_warehouse@OData.Community.Display.V1.FormattedValue")]
        public string? WareHouse { get; set; }

        [JsonPropertyName("_hbb_customer_segment_value@OData.Community.Display.V1.FormattedValue")]
        public string? Segment { get; set; }

        [JsonPropertyName("hbb_customer_saleschannel@OData.Community.Display.V1.FormattedValue")]
        public string? SalesChannel { get; set; }
    }
}